# Question - 1
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3,5,6 and 9. The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.


n = 1000
sum = 0
for num in range(1,n):
    if num%3==0 or num%5==0:
        sum = sum + num
print(sum)





# Question - 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89,......
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


first = 1
second = 2
result = [second]

while True: 
    fibonacci = first + second 
    first = second 
    second = fibonacci
    
    if fibonacci > 4000000:
        break 
    if fibonacci % 2 == 0:
        result.append(fibonacci)
total_sum = sum(result)
print(total_sum)

